import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:tsukuyomi_space_app/core/llm_client.dart';
import 'package:tsukuyomi_space_app/core/models.dart';
import 'package:tsukuyomi_space_app/core/room_conversation.dart';

List<Map<String, String>> expandMessages(List<dynamic> items) => [
  for (final item in items)
    {
      'role': item['role'] as String,
      'turnId': item['turnId'] as String,
      'content': (item['contentSegments'] as List)
          .map((segment) => (segment[0] as String) * (segment[1] as int))
          .join(),
    },
];

ChatTurn turn(String id, String question, String answer) => ChatTurn(
  id: id,
  user: question,
  assistant: answer,
  createdAt: DateTime.utc(2026, 9, 30),
);

void main() {
  // Expectations were generated by the original website implementation at the
  // commit recorded in this fixture, including its UTF-16 slicing semantics.
  final fixtures = jsonDecode(
    File('test/fixtures/room_conversation_web.json').readAsStringSync(),
  ) as Map;
  for (final fixture in fixtures['cases'] as List) {
    test('website conversation parity: ${fixture['name']}', () {
      final history = expandMessages(fixture['history'] as List);
      final options = fixture['options'] as Map? ?? {};
      final selected = selectRecentRoomConversation(
        history,
        maxChars: options['maxChars'] as int? ?? 6000,
        maxMessages: options['maxMessages'] as int? ?? 12,
      );
      expect(selected, expandMessages(fixture['expected'] as List));
      expect(
        selected.fold<int>(0, (sum, item) => sum + item['content']!.length),
        lessThanOrEqualTo(
          ((options['maxChars'] as int? ?? 6000) == 0
                  ? 6000
                  : options['maxChars'] as int? ?? 6000)
              .clamp(500, 30000),
        ),
      );
    });
  }

  test('selection does not mutate the stored conversation', () {
    final history = [
      {'role': 'user', 'content': '  原始问题  ', 'turnId': 'latest'},
      {'role': 'assistant', 'content': 'a' * 7000, 'turnId': 'latest'},
    ];
    final before = jsonEncode(history);
    selectRecentRoomConversation(history);
    expect(jsonEncode(history), before);
  });

  final variants = [
    ('openai', 'https://provider.example/v1/chat/completions', false),
    ('responses', 'https://provider.example/v1/responses', false),
    ('anthropic', 'https://provider.example/v1/messages', false),
    ('ollama', 'http://localhost:11434/api/chat', false),
    ('website proxy', 'https://provider.example/v1/chat/completions', true),
  ];
  for (final (protocol, endpoint, proxy) in variants) {
    test(
      '$protocol sends bounded paired history without app metadata',
      () async {
        final history = [
          turn('older', 'old-question', 'o' * 4000),
          turn('latest', '最近这个问题仍必须送到模型', '开始${'a' * 6996}结束'),
        ];
        final expected =
            selectRecentRoomConversation([
                  for (final item in history) ...[
                    {'role': 'user', 'content': item.user, 'turnId': item.id},
                    {
                      'role': 'assistant',
                      'content': item.assistant,
                      'turnId': item.id,
                    },
                  ],
                ], maxChars: protocol == 'ollama' ? 4000 : 6000)
                .map(
                  (item) => {'role': item['role'], 'content': item['content']},
                )
                .toList();
        var calls = 0;
        final client = LlmClient(
          clientFactory: () => MockClient((request) async {
            calls++;
            final body = jsonDecode(request.body) as Map;
            expect(request.method, 'POST');
            expect(
              request.url.toString(),
              proxy ? 'https://site.example/api/chat/stream' : endpoint,
            );
            final List messages;
            if (proxy) {
              expect(request.headers['cookie'], 'session=test');
              expect(body['message'], '新的问题');
              messages = body['conversation'] as List;
            } else {
              expect(request.headers['cookie'], isNull);
              final all =
                  body[protocol == 'responses' ? 'input' : 'messages'] as List;
              messages = [
                for (final item in all.take(all.length - 1))
                  if (item['role'] != 'system') item,
              ];
              expect(all.last['role'], 'user');
              expect(
                protocol == 'responses'
                    ? all.last['content'][0]['text']
                    : all.last['content'],
                '新的问题',
              );
            }
            expect(messages, expected);
            expect(
              messages.where((item) => item['content'] == history.last.user),
              hasLength(1),
            );
            expect(messages.last['content'], startsWith('开始'));
            expect(messages.last['content'], endsWith('结束'));
            expect(messages.last['content'], contains('[较早内容省略]'));
            expect(messages.every((item) => item.length == 2), isTrue);
            return http.Response(
              jsonEncode({'reply': 'ok'}),
              200,
              headers: {'content-type': 'application/json'},
            );
          }),
        )..siteCookie = 'session=test';
        expect(
          await client
              .reply(
                RoomSettings(
                  siteUrl: 'https://site.example',
                  llmUrl: endpoint,
                  model: 'test',
                  demo: false,
                  options: {'llmProxy': proxy},
                ),
                history,
                '新的问题',
              )
              .join(),
          'ok',
        );
        expect(calls, 1);
      },
    );
  }
}
