name: tsukuyomi_space_app
description: Native Flutter Room client for Tsukuyomi Space.
publish_to: none
version: 0.6.8+14
environment:
  sdk: ^3.13.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  crypto: ^3.0.7
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.3
  audioplayers: ^6.5.1
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  tsukuyomi_live2d:
    path: packages/tsukuyomi_live2d
  cupertino_icons: ^1.0.9
  url_launcher: ^6.3.2
  flutter_widget_from_html_core: ^0.17.4
  flutter_markdown_plus: ^1.0.12
  markdown: ^7.3.1
  flutter_math_fork: ^0.7.4
  highlight: ^0.7.0
  forge2d: 0.14.2+1
  html: ^0.15.7
  image: ^4.10.1
  file_selector: ^1.1.0
  flutter_inappwebview: ^6.1.5
  geolocator: ^14.1.1
  share_plus: ^13.3.0
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  shaders:
    - assets/shaders/kaguya_effect.frag
  assets:
    - assets/images/
    - assets/images/sakura/
    - assets/live2d/
    - assets/live2d/textures/
    - assets/game/
