import 'package:flutter/widgets.dart';

import '../../core/site_localization.dart';

String userCenterCopy(BuildContext context, String key) {
  final language = SiteLocaleScope.maybeOf(context)?.language ?? 'zh';
  return _messages[language]?[key] ?? _messages['zh']![key] ?? key;
}

const _messages = <String, Map<String, String>>{
  'en': {
    "account": "My account",
    "creative": "Create & connect",
    "materials": "My materials",
    "search": "Find a section",
    "noSections": "No matching sections",
    "clearSearch": "Clear search",
    "refreshArticles": "Refresh articles",
    "messages": "My messages",
    "bookmarks": "Bookmarks",
    "pixels": "Pixel art",
    "gallery": "Gallery",
    "attachments": "Attachments",
    "publicProfile": "Public profile",
    "accountInfo": "View account information",
    "profileHint": "Choose the name and introduction people see.",
    "avatarHint": "Update your avatar",
    "discard": "Reset changes",
    "unsaved": "Unsaved changes",
    "saved": "Your profile is up to date",
    "growth": "Bond growth",
    "growthHint": "A little connection, every day.",
    "growthOpen": "Check in & view tasks",
    "growthUnavailable": "Growth is unavailable right now.",
    "maxLevel": "Max level",
    "xp": "XP",
    "security": "Account security",
    "email": "Email",
    "qq": "QQ login",
    "linked": "Linked",
    "unlinked": "Not linked",
    "securityOpen": "Manage account security",
    "room": "Yachiyo is here",
    "roomHint": "Take a moment, make yourself at home.",
    "roomOpen": "Enter room",
    "navigation": "User center sections",
    "refresh": "Refresh account data",
    "noMatches": "No matching results",
    "searchHint": "Try another keyword or clear the search.",
  },
  'ja': {
    "account": "マイアカウント",
    "creative": "創作と交流",
    "materials": "マイ素材",
    "search": "機能を探す",
    "noSections": "該当する機能はありません",
    "clearSearch": "検索を解除",
    "refreshArticles": "記事を更新",
    "messages": "自分の投稿",
    "bookmarks": "ブックマーク",
    "pixels": "ピクセルアート",
    "gallery": "ギャラリー",
    "attachments": "添付ファイル",
    "publicProfile": "公開プロフィール",
    "accountInfo": "アカウント情報を見る",
    "profileHint": "表示する名前と自己紹介を編集できます。",
    "avatarHint": "アバターを変更",
    "discard": "変更を戻す",
    "unsaved": "未保存の変更",
    "saved": "プロフィールは保存されています",
    "growth": "月契成長",
    "growthHint": "毎日の小さなつながり。",
    "growthOpen": "チェックインとタスク",
    "growthUnavailable": "成長記録を読み込めません。",
    "maxLevel": "最高レベル",
    "xp": "EXP",
    "security": "アカウント安全",
    "email": "メール",
    "qq": "QQ ログイン",
    "linked": "連携済み",
    "unlinked": "未連携",
    "securityOpen": "安全設定へ",
    "room": "八千代はここにいます",
    "roomHint": "ひと息ついて、ゆっくり過ごしましょう。",
    "roomOpen": "部屋へ",
    "navigation": "ユーザーセンターの機能",
    "refresh": "アカウント情報を更新",
    "noMatches": "該当する結果はありません",
    "searchHint": "別のキーワードを試すか、検索を解除してください。",
  },
  'zh': {
    "account": "我的账号",
    "creative": "创作与互动",
    "materials": "我的素材",
    "search": "搜索功能",
    "noSections": "没有找到相关功能",
    "clearSearch": "清除搜索",
    "refreshArticles": "刷新文章",
    "messages": "我的留言",
    "bookmarks": "我的收藏",
    "pixels": "像素画",
    "gallery": "图库管理",
    "attachments": "附件库",
    "publicProfile": "公开主页",
    "accountInfo": "查看账号信息",
    "profileHint": "让大家通过昵称和简介认识你。",
    "avatarHint": "更换头像",
    "discard": "还原修改",
    "unsaved": "有尚未保存的修改",
    "saved": "资料已保存",
    "growth": "月契成长",
    "growthHint": "每天一点相伴，慢慢积累。",
    "growthOpen": "签到与查看任务",
    "growthUnavailable": "暂时无法读取成长记录。",
    "maxLevel": "已到最高等级",
    "xp": "经验",
    "security": "账号安全",
    "email": "邮箱",
    "qq": "QQ 登录",
    "linked": "已绑定",
    "unlinked": "未绑定",
    "securityOpen": "管理账号安全",
    "room": "八千代在这里",
    "roomHint": "和八千代一起，把时间慢下来。",
    "roomOpen": "进入房间",
    "navigation": "用户中心功能",
    "refresh": "刷新账号资料",
    "noMatches": "没有匹配的内容",
    "searchHint": "换一个关键词，或清除搜索查看全部。",
  },
};
