// Generate immutable semantic definitions and exact director prompts from the
// adjacent original website without modifying it.
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const root = path.resolve(process.argv[2] || '../tsukuyomi-space');
const read = file => fs.readFileSync(path.join(root, 'src/frontend', file), 'utf8');
const strip = source => source.replace(/^\uFEFF/, '').replace(/^import[\s\S]*?;\s*/gm, '').replace(/\bexport\s+/g, '');
function evaluate(file, names, globals = {}) {
  return vm.runInNewContext(`(function(){${strip(read(file))};return {${names.join(',')}}})()`, globals);
}
const registry = evaluate('constants/room/behaviorActionRegistry.js', ['BEHAVIOR_ACTION_DEFINITIONS', 'semanticActionPromptCatalog', 'behaviorBodyPoseManifestItems']);
const reference = JSON.parse(fs.readFileSync('lib/core/room_reference_data.dart','utf8').match(/r'''(.*)'''/s)[1]);
const manifest = evaluate('constants/room/live2dManifest.js', ['live2DPromptCatalog'], {
  behaviorBodyPoseManifestItems: registry.behaviorBodyPoseManifestItems,
  semanticExpressionManifestItems: () => reference.live2d.expressions,
});
const prompts = evaluate('services/room/live2dLlmControl.js', ['live2DControlSystemPrompt', 'live2DStreamingControlSystemPrompt'], {
  live2DPromptCatalog: manifest.live2DPromptCatalog,
  live2DSemanticPromptCatalog: () => `${registry.semanticActionPromptCatalog()}\nOutput semantic actions only; the room runtime maps those actions through BehaviorPlan, local Cubism parameters, stage pose, blink, mouth, breath, and accessory physics.`,
});
const actions = registry.BEHAVIOR_ACTION_DEFINITIONS.map(definition => {
  const item = {...definition};
  delete item.parameters; delete item.fallbackPattern;
  item.fallbackPattern = definition.fallbackPattern?.source || '';
  item.caseInsensitive = definition.fallbackPattern?.flags.includes('i') || false;
  // Every original target is affine in action.intensity; preserve constants,
  // all side-dependent parameter ids and coefficients rather than flattening.
  item.targets = Object.fromEntries(['', 'left', 'right', 'up', 'down'].map(side => {
    const sample = intensity => definition.parameters?.({intensity, side, durationMs: definition.defaultDurationMs, delayMs: 0}) || [];
    const zero = sample(0), full = sample(1);
    return [side, full.map((p, i) => ({...p, constant: zero[i].value, coefficient: p.value - zero[i].value}))];
  }));
  return item;
});
const matchers = evaluate('services/room/live2dControl.js', ['textExpressionMatchers']).textExpressionMatchers;
const data = {actions, emotionMatchers: matchers.map(m => ({...m, pattern:m.pattern.source})), controlPrompt: prompts.live2DControlSystemPrompt(), streamingPrompt: prompts.live2DStreamingControlSystemPrompt()};
fs.writeFileSync('lib/live2d/live2d_semantic_data.dart', `// Generated by tool/sync_live2d_semantics.mjs from the original site.\nconst live2dSemanticJson = r'''${JSON.stringify(data)}''';\n`);
console.log(`Generated ${actions.length} semantic actions with original prompts.`);
