// Copy every original locale key into native data. Does not modify the website.
// Usage: node tool/sync_site_i18n.mjs ../tsukuyomi-space
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';

const root = path.resolve(process.argv[2] || '../tsukuyomi-space');
const read = name => fs.readFileSync(path.join(root, 'src/frontend/i18n', name), 'utf8');
const strip = source => source.replace(/^import[^;]+;\s*/gm, '').replace(/export\s+(?=const)/g, '');
const { en } = vm.runInNewContext(`(function(){${strip(read('messages.en.js'))};return {en};})()`, {}, {timeout: 1000});
const { i18n } = vm.runInNewContext(`(function(){${strip(read('messages.js'))};return {i18n};})()`, {en}, {timeout: 1000});
const navigation = fs.readFileSync(path.join(root, 'src/frontend/services/siteNavigation.js'), 'utf8');
const navigationCopy = vm.runInNewContext(`(function(){${navigation.slice(0,navigation.indexOf('const aliases'))};return copy;})()`, {}, {timeout:1000});
const pet = fs.readFileSync(path.join(root, 'src/frontend/components/SitePet.vue'), 'utf8');
const petStart = pet.indexOf('const COPY ='), petEnd = pet.indexOf('\n\nconst frame',petStart);
const petData = vm.runInNewContext(`(function(){${pet.slice(petStart,petEnd)};return {COPY,GUIDES};})()`, {}, {timeout:1000});
function flatten(value, prefix = '', target = {}) {
  if (typeof value === 'string') target[prefix] = value;
  else for (const [key,item] of Object.entries(value)) flatten(item, prefix ? `${prefix}.${key}` : key, target);
  return target;
}
const extras = {};
const nativeCopy = JSON.parse(fs.readFileSync('tool/native_ui_copy.json','utf8'));
for (const language of ['zh','ja','en']) {
  extras[language] = {
    ...flatten(navigationCopy[language], 'navigation'),
    ...flatten(petData.COPY[language], 'guide'),
    ...Object.fromEntries(petData.GUIDES.flatMap(item => item[language].map((value,index) => [`guide.pages.${item.key}.${index}`,value]))),
  };
  for (const [zh,ja,en] of nativeCopy) {
    const key = `nativeUi.${crypto.createHash('sha1').update(zh).digest('hex').slice(0,12)}`;
    extras[language][key] = ({zh,ja,en})[language].replaceAll('\\n','\n');
  }
  extras[language].nativeEditorCharacters = {zh:'{count} 字符 · 草稿自动保存在当前站点与账号下',ja:'{count}文字 · 下書きは現在のサイトとアカウントに自動保存されます',en:'{count} characters · Drafts save automatically for this site and account'}[language];
  extras[language].nativeAuthResendSeconds = {zh:'{count}s 后重发',ja:'{count}秒後に再送',en:'Resend in {count}s'}[language];
  extras[language].nativeLive2DAudienceQueue = {zh:'{count} 条留言等待回应',ja:'{count}件のメッセージが返答待ち',en:'{count} messages waiting for a response'}[language];
  extras[language].nativeAssetPagination = {zh:'{total} 项 · 第 {page} / {pages} 页',ja:'{total}件 · {page} / {pages}ページ',en:'{total} items · Page {page} / {pages}'}[language];
}
const literal = value => JSON.stringify(value).replaceAll('$', '\\$');
let output = '// Generated by tool/sync_site_i18n.mjs. All keys from source messages.js/messages.en.js.\n';
output += 'const nativeSiteMessages = <String, Map<String, String>>{\n';
for (const language of ['zh', 'ja', 'en']) {
  const messages = i18n[language];
  if (!messages || Object.values(messages).some(value => typeof value !== 'string')) throw new Error(`Unsupported ${language} messages`);
  output += `  ${literal(language)}: {\n`;
  for (const [key,value] of Object.entries(messages)) output += `    ${literal(key)}: ${literal(value)},\n`;
  output += '  },\n';
}
output += '};\n';
output += 'const nativeSiteSupplementalMessages = <String, Map<String, String>>{\n';
for (const language of ['zh','ja','en']) {
  output += `  ${literal(language)}: {\n`;
  for (const [key,value] of Object.entries(extras[language])) output += `    ${literal(key)}: ${literal(value)},\n`;
  output += '  },\n';
}
output += '};\n';
fs.writeFileSync('lib/core/site_i18n_messages.dart', output);
console.log(Object.fromEntries(Object.entries(i18n).map(([lang,messages]) => [lang,Object.keys(messages).length])));
console.log('Navigation / guide keys:', Object.keys(extras.zh).length);
